<?php

namespace AppBundle\Repository;

/**
 * CustomerVehiclesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerVehiclesRepository extends \Doctrine\ORM\EntityRepository
{
}
