<?php

namespace AppBundle\Repository;

/**
 * DriverDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
