<?php

namespace AppBundle\Repository;

/**
 * LeadFollowupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadFollowupRepository extends \Doctrine\ORM\EntityRepository
{
}
