<?php

namespace AppBundle\Repository;

/**
 * LeadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadsRepository extends \Doctrine\ORM\EntityRepository
{
}
