<?php

namespace AppBundle\Repository;

/**
 * TripScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
