<?php

namespace AppBundle\Repository;

/**
 * TripLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripLogsRepository extends \Doctrine\ORM\EntityRepository
{
}
