<?php

namespace AppBundle\Repository;

/**
 * UserContactNosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserContactNosRepository extends \Doctrine\ORM\EntityRepository
{
}
