<?php

namespace AppBundle\Repository;

/**
 * UserAddressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAddressesRepository extends \Doctrine\ORM\EntityRepository
{
}
